### ISSUE TITLE
[ANT-828] nb_cores - Enhance Application Configuration Documentation

### ISSUE THREAD

**Issue by laurent-laporte-pro** [AntaresSimulatorTeam/AntaREST#1707]
## Current Documentation Status

The documentation regarding the [application configuration](https://antares-web.readthedocs.io/en/latest/install/1-CONFIG/) is currently partially covered in the document `docs/install/1-CONFIG.md`. However, it is essential to update this documentation as it is currently quite concise. The goal is to provide a comprehensive and detailed description of each object and configuration parameter in this document.

Additionally, it is necessary to update the comments within the files `resources/application.yaml`, `resources/deploy/config.yaml`, and `resources/deploy/config.prod.yaml` to document any new parameters introduced.

## Enhancement Details

- **Documentation Update**: The existing documentation in `docs/install/1-CONFIG.md` needs to be expanded and improved to provide a complete and detailed explanation of each configuration object and parameter. This should include usage examples, potential values, and any dependencies or interactions with other configuration settings.

- **Comment Updates**: Comments within the configuration files (`resources/application.yaml`, `resources/deploy/config.yaml`, and `resources/deploy/config.prod.yaml`) should be updated to reflect any new configuration parameters. These comments should be in English and provide clear explanations of each parameter's purpose and usage.

## Example

```yaml
security:
  disabled: false
  jwt:
    key: super-secret  # JWT secret key for authentication
  login:
    admin:
      pwd: admin  # Admin user's password
  external_auth:
    url: ""  # External authentication URL (empty for local authentication)
    default_group_role: 10  # Default user role for external authentication
    add_ext_groups: false  # Whether to add external groups to user roles

db:
  url: "sqlite:///database.db"  # Database URL (SQLite in this case)
  #pool_recycle:  # Database connection pool recycling configuration (commented out)

storage:
  tmp_dir: /tmp  # Temporary directory for storing temporary files
  matrixstore: /home/john/Projects/antarest_data/matrices  # Directory for matrix storage
  archive_dir: /home/john/Projects/antarest_data/archives  # Directory for study archives
  allow_deletion: false  # Indicates if studies found in non-default workspace can be deleted by the application
  #matrix_gc_sleeping_time: 3600  # Time in seconds to sleep between two garbage collections (commented out)
  workspaces:
    default:  # Default workspace configuration
      path: /home/john/Projects/antarest_data/internal_studies/  # Path to the default workspace
    studies:  # Configuration for the "studies" workspace
      path: /home/john/Projects/antarest_data/studies/  # Path to the "studies" workspace
    staging_studies:  # Configuration for the "staging_studies" workspace
      path: /home/john/Projects/antarest_data/staging_studies/  # Path to the "staging_studies" workspace

launcher:
  default: local  # Default launcher configuration (local in this case)
  local:
    enable_nb_cores_detection: True  # Enable detection of available CPU cores
    binaries:
      # Binary paths for various versions of the launcher
      700: /home/john/opt/antares-8.2.3-Ubuntu-20.04/bin/antares-8.2-solver
      720: /home/john/opt/antares-8.2.3-Ubuntu-20.04/bin/antares-8.2-solver
      # Additional versions can be configured similarly
  slurm:
    local_workspace: /home/john/Projects/antarest_data/slurm_workspace  # Path to the local SLURM workspace
    username: run-antares  # SLURM username
    hostname: 10.134.248.111  # SLURM server hostname
    port: 22  # SSH port for SLURM
    private_key_file: /home/john/.ssh/id_rsa  # SSH private key file
    default_wait_time: 900  # Default wait time for SLURM jobs
    default_time_limit: 172800  # Default time limit for SLURM jobs
    enable_nb_cores_detection: False  # Enable detection of available CPU cores for SLURM
    nb_cores:
      min: 1  # Minimum number of CPU cores
      default: 22  # Default number of CPU cores
      max: 24  # Maximum number of CPU cores
    default_json_db_name: launcher_db.json  # Default JSON database name for SLURM
    slurm_script_path: /applis/antares/launchAntares.sh  # Path to the SLURM script
    db_primary_key: name  # Primary key for the SLURM database
    antares_versions_on_remote_server:
      # List of Antares versions available on the remote SLURM server

debug: false  # Disable debugging (true or false)

root_path: ""  # Root path (empty for default)

server:
  worker_threadpool_size: 12  # Size of the worker thread pool
  services:
    - watcher  # Enable the "watcher" service
    - matrix_gc  # Enable the "matrix_gc" service

logging:
  level: INFO  # Logging level (INFO, DEBUG, etc.)
  #logfile: ./tmp/antarest.log  # Path to the log file (commented out)
  #json: false  # Enable JSON logging (commented out)

# Uncomment these lines to use Redis as a backend for the eventbus
# It is required to use Redis when using this application on multiple workers in a preforked model like Gunicorn, for instance
#eventbus:
#  redis:
#    host: localhost  # Redis host
#    port: 6379  # Redis port
```
